# Generated by Django 4.2.24 on 2025-09-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='accounts.module'),
        ),
    ]
