# Generated by Django 4.2.24 on 2025-09-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_populate_module_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
