# Generated by Django 4.2.24 on 2025-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_closes_at_exam_duration_minutes_exam_opens_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='question_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
